allow-branch = ["main", "dev", "!HEAD"]
publish = false
pre-release-hook = ["git", "cliff", "-o", "CHANGELOG.md", "--tag", "{{version}}" ]
pre-release-commit-message = "chore: Release worship presentations version {{version}}"
tag-message = "chore: Release worship presentations version {{version}}"
tag-name = "v{{version}}"
